# Generated by Django 2.2.10 on 2020-02-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=4)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('major', models.CharField(max_length=10)),
                ('marital_Status', models.BooleanField()),
                ('core_strength', models.TextField()),
                ('career', models.TextField()),
                ('img_profile', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
