# Generated by Django 2.2.10 on 2020-03-06 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name': '장소1',
                'verbose_name_plural': '장소1 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant1',
            fields=[
                ('place1_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='restaurant1', related_query_name='restaurant1_by_oto', serialize=False, to='multitable.Place1')),
                ('hot_dogs', models.BooleanField(default=False)),
                ('pizza', models.BooleanField(default=False)),
                ('near_places', models.ManyToManyField(related_name='restaurant1_set', related_query_name='restaurant1_by_near_places', to='multitable.Place1')),
            ],
            bases=('multitable.place1',),
        ),
    ]
