# Generated by Django 2.2.10 on 2020-03-05 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0003_auto_20200305_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('counterpart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterpart_relation_set', to='many_to_many.InstagramUser')),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_relation_set', to='many_to_many.InstagramUser')),
            ],
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='many_to_many.Relation', to='many_to_many.InstagramUser'),
        ),
        migrations.CreateModel(
            name='FaceBookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('friends', models.ManyToManyField(related_name='_facebookuser_friends_+', to='many_to_many.FaceBookUser')),
            ],
        ),
    ]
